### ISSUE TITLE
Clang Language Server server crashed

### ISSUE THREAD

**Issue by DuanYuFi** [secretflow/devtools#11]
I ran the script to generate the `compile_commands.json`. But my Clang crashed every time when starting. The error log is
```
The Clang Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```
I am using clangd version 13.0.1 (Anolis 13.0.1-2.0.2.module+an8.7.0+10996+1588f068), with vscode extension version v0.1.23.

full output of clangd extension is below
[output.log](https://github.com/secretflow/devtools/files/10834111/output.log)

**Comment by anakinxc** [comment]
Hi @DuanYuFi 

Stacktrace points to somewhere inside sema, should be a clangd issue.

Can you try latest clangd? Should be 15.0.7

**Comment by DuanYuFi** [comment]
Oh, I thought it was the latest. I'll try it tomorrow. Thanks.

**Comment by DuanYuFi** [comment]
Clangd doesn't crash now. But it seems that some standard library header files cannot be found. For example:
```
In included file: 'stddef.h' file not foundclang(pp_file_not_found)
stdlib.h(31, 10): Error occurred here
In included file: no type named 'ParamType' in 'spu::mpc::test::ApiTest_add_ss_Test'clang(typename_nested_not_found)
```
when I try to include "libspu/mpc/api_test.h".

Do you have any idea on how to solve this problem?

**Comment by anakinxc** [comment]
Hi @DuanYuFi 

Can you provide details about how you installed clangd?

Best

**Comment by DuanYuFi** [comment]
1. Install the release from [](https://github.com/clangd/clangd/releases)
2. Unzip and move the binary to `/usr/bin`, move lib to /usr/local/lib
3. Install vscode extension for clangd
4. Save the script in this repo and run to generate `compile_commands.json`
That's all. Hope it could provide the sufficient information for you. :)

**Comment by DuanYuFi** [comment]
*typo: from [github](https://github.com/clangd/clangd/releases)

**Comment by DuanYuFi** [comment]
Life is short, don't spend it on setting environment. I changed a machine and all works.
